### ISSUE TITLE
Missing built-in properties in .NET SDK

### ISSUE THREAD

**Issue by kzu** [mhutch/MonoDevelop.MSBuildEditor#115]
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/169707/c90ed046-d1db-47c6-bb0d-1ecd0f767809)

This property (as well as `RootNamespace`, `TargetFramework`, etc.) is used throughout the .NET SDK, yet it's flagged as unused or misspelled.

**Comment by mhutch** [comment]
Those should definitely have been pulled in from the `Microsoft.NET.Sdk` import. Are there any errors in the output window?

**Comment by kzu** [comment]
Got latest, enabled, this is the exception:

```
Error: Failed to initialize MSBuild runtime info
  System.NullReferenceException: Object reference not set to an instance of an object.
     at MonoDevelop.MSBuild.CurrentProcessMSBuildEnvironment.GetImportSearchPaths(Toolset toolset) in D:\a\MonoDevelop.MSBuildEditor\MonoDevelop.MSBuildEditor\MonoDevelop.MSBuild\CurrentProcessMSBuildEnvironment.cs:line 94
     at MonoDevelop.MSBuild.CurrentProcessMSBuildEnvironment..ctor(ILogger logger) in D:\a\MonoDevelop.MSBuildEditor\MonoDevelop.MSBuildEditor\MonoDevelop.MSBuild\CurrentProcessMSBuildEnvironment.cs:line 35
     at MonoDevelop.MSBuild.Editor.Completion.MSBuildParserProvider..ctor(XmlParserProvider xmlParserProvider, MSBuildEnvironmentLogger environmentLogger, BackgroundParseServiceProvider parseServiceProvider, ITaskMetadataBuilder taskMetadataBuilder, MSBuildSchemaProvider schemaProvider, IMSBuildEnvironment msbuildEnvironment) in D:\a\MonoDevelop.MSBuildEditor\MonoDevelop.MSBuildEditor\MonoDevelop.MSBuild.Editor\MSBuildParserProvider.cs:line 

```

**Comment by kzu** [comment]
Indeed it is! Thanks! 🙏
